### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by craigmulligan** [Agile-IoT/agile-sdk#3]
Need to set up a web accessible agile core so tests can run in a CI. (Also need to write the tests).

**Comment by craigmulligan** [comment]
@cskiraly does create-net still have that device that is exposed to the web?

**Comment by cskiraly** [comment]
not anymore, but we could have one. Alternatively, we can have one started automatically on x86 emulation.

**Comment by craigmulligan** [comment]
We now have this set up. But only running a few tests, need to write more.
