### ISSUE TITLE
/dist folder missing in latest push

### ISSUE THREAD

**Issue by agribu** [Agile-IoT/agile-sdk#40]
I installed the public available agile-sdk package, following the instruction: `npm install --save agile-sdk` in my nodejs project folder. However, after requiring the module in my nodejs project and executing it, the following message is displayed:
```diff
-Error: Cannot find module './dist/index.js'
```

**Comment by craigmulligan** [comment]
Hey @agribu, I just installed it and couldn't reproduce this, are you still seeing issues? If so could you send me a minimal project that reproduces the issue?

**Comment by agribu** [comment]
Seems to be fixed now. Closing this issue.
